---
kind: pipeline
type: docker
name: build

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: build-backend
    image: plugins/docker
    settings:
      repo: registry.wtf-eg.net/solar/backend
      registry: registry.wtf-eg.net
      username:
        from_secret: "docker_username"
      password:
        from_secret: "docker_password"

