"""fix?

Revision ID: 168c4e550c33
Revises: f4cbcbadddda
Create Date: 2025-10-20 23:46:15.254251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168c4e550c33'
down_revision: Union[str, None] = 'f4cbcbadddda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverter', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_inverter_time'), table_name='inverter_measurements')
    op.drop_index(op.f('idx_user_time'), table_name='inverter_measurements')
    op.drop_index(op.f('inverter_measurements_time_idx'), table_name='inverter_measurements')
    op.drop_index(op.f('inverter_measurements_user_id_time_idx'), table_name='inverter_measurements')
    op.add_column('user', sa.Column('tmp_pass', sa.String(), nullable=True))
    op.add_column('user', sa.Column('api_key', sa.String(length=32), nullable=True))
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_unique_constraint(None, 'user', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'api_key')
    op.drop_column('user', 'tmp_pass')
    op.create_index(op.f('inverter_measurements_user_id_time_idx'), 'inverter_measurements', ['user_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('inverter_measurements_time_idx'), 'inverter_measurements', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_user_time'), 'inverter_measurements', ['user_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_inverter_time'), 'inverter_measurements', ['inverter_id', sa.literal_column('time DESC')], unique=False)
    op.alter_column('inverter', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
