"""convert dc channel measurements to integer

Revision ID: 1a89fa2e85eb
Revises: 5768939010d0
Create Date: 2025-11-19 12:07:37.690225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a89fa2e85eb'
down_revision: Union[str, None] = '5768939010d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dc_channel_measurements', 'power',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='power::integer')
    op.alter_column('dc_channel_measurements', 'voltage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='voltage::integer')
    op.alter_column('dc_channel_measurements', 'yield_day_wh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='yield_day_wh::integer')
    op.alter_column('dc_channel_measurements', 'yield_total_kwh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='yield_total_kwh::integer')
    op.alter_column('dc_channel_measurements', 'irradiation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='irradiation::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dc_channel_measurements', 'irradiation',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('dc_channel_measurements', 'yield_total_kwh',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('dc_channel_measurements', 'yield_day_wh',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('dc_channel_measurements', 'voltage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('dc_channel_measurements', 'power',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
