"""inverter model extended

Revision ID: 1d006d59a0fb
Revises: 
Create Date: 2024-02-02 16:10:51.905295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d006d59a0fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inverter', sa.Column('rated_power', sa.Integer(), nullable=True))
    op.add_column('inverter', sa.Column('number_of_mppts', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'inverter', ['serial_logger'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inverter', type_='unique')
    op.drop_column('inverter', 'number_of_mppts')
    op.drop_column('inverter', 'rated_power')
    # ### end Alembic commands ###
