"""add api_key to user table

Revision ID: a0d10f46b03b
Revises: 168c4e550c33
Create Date: 2025-10-20 23:49:00.366475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d10f46b03b'
down_revision: Union[str, None] = '168c4e550c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(32), nullable=True))
    with op.batch_alter_table('user') as batch_op:
        batch_op.create_unique_constraint('uq_user_api_key', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('uq_user_api_key')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
