"""remove legacy tmp_pass field from user model

Revision ID: a9357e3d02f5
Revises: d8f09ab046bf
Create Date: 2025-10-25 16:53:26.314883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9357e3d02f5'
down_revision: Union[str, None] = 'd8f09ab046bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('dc_channel_measurements_time_idx'), table_name='dc_channel_measurements')
    op.drop_index(op.f('dc_channel_measurements_user_id_time_idx'), table_name='dc_channel_measurements')
    op.drop_index(op.f('idx_dc_channel'), table_name='dc_channel_measurements')
    op.drop_index(op.f('idx_dc_inverter_time'), table_name='dc_channel_measurements')
    op.drop_index(op.f('idx_dc_user_time'), table_name='dc_channel_measurements')
    op.drop_column('user', 'tmp_pass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tmp_pass', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_dc_user_time'), 'dc_channel_measurements', ['user_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_dc_inverter_time'), 'dc_channel_measurements', ['inverter_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_dc_channel'), 'dc_channel_measurements', ['inverter_id', 'channel', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('dc_channel_measurements_user_id_time_idx'), 'dc_channel_measurements', ['user_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('dc_channel_measurements_time_idx'), 'dc_channel_measurements', [sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
