"""tmp_password removed

Revision ID: f16b15d226cd
Revises: 1d006d59a0fb
Create Date: 2025-05-28 21:05:50.416317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16b15d226cd'
down_revision: Union[str, None] = '1d006d59a0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tmp_pass')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tmp_pass', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
